CREATE TABLE `ITEM_INFO` (
  `ES_ID` varchar(100) NOT NULL COMMENT '下载编号',
  `PRODUCT_NAME` varchar(500) NOT NULL COMMENT '产品名称',
  `APPROVAL_NUM` varchar(100) NOT NULL COMMENT '注册证编号',
  `ENTERPRISE` varchar(500) NOT NULL COMMENT '注册人名称',
  `ENTERPRISE_ADDRESS` varchar(500) DEFAULT NULL COMMENT '注册人住所',
  `APPROVAL_DATE` varchar(20) DEFAULT NULL COMMENT '批准日期',
  `EXPIRED_DATE` varchar(20) DEFAULT NULL COMMENT '过期日期',
  PRIMARY KEY (`ES_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='任务基本信息表';

CREATE TABLE `ITEM_IP_BLACKLIST` (
  `IP` varchar(100) NOT NULL COMMENT 'ip地址',
  PRIMARY KEY (`IP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='不可用ip名单';